
<!DOCTYPE html>
<!--[if IE]><![endif]-->
<!--[if IE 8 ]><html dir="ltr" lang="en" class="ie8"><![endif]-->
<!--[if IE 9 ]><html dir="ltr" lang="en" class="ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html dir="ltr" lang="en">
<!--<![endif]-->
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>More Business</title>
<script src="catalog/view/javascript/jquery/jquery-2.1.1.min.js" type="text/javascript"></script>
<link href="catalog/view/javascript/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen" />
<script src="catalog/view/javascript/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="catalog/view/javascript/inspire/product-slider-zoom/jquery.elevatezoom.js" type="text/javascript"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="//fonts.googleapis.com/css?family=Open+Sans:400,400i,300,700" rel="stylesheet" type="text/css" />
<link href="catalog/view/theme/default/stylesheet/stylesheet.css" rel="stylesheet">
<script src="catalog/view/javascript/countdown/jquery.plugin.min.js" type="text/javascript"></script>
<script src="catalog/view/javascript/countdown/jquery.countdown.min.js" type="text/javascript"></script>
<link href="catalog/view/javascript/jquery/magnific/magnific-popup.css" type="text/css" rel="stylesheet" media="screen" />
<link href="catalog/view/theme/default/stylesheet/inspirenewsletter.css" type="text/css" rel="stylesheet" media="screen" />
<script src="catalog/view/javascript/blog/lightbox-2.6.min.js" type="text/javascript"></script>
<link href="catalog/view/javascript/blog/lightbox.css" rel="stylesheet" type="text/css" />

<script src="catalog/view/javascript/inspire/custom.js" type="text/javascript"></script>

<script src="catalog/view/javascript/jquery/magnific/jquery.magnific-popup.min.js" type="text/javascript"></script>
<script src="catalog/view/javascript/jquery/inspirequickview.js" type="text/javascript"></script>
<script src="catalog/view/javascript/jquery/inspirenewsletter.js" type="text/javascript"></script>
<script src="catalog/view/javascript/common.js" type="text/javascript"></script>



</head>
<body>

<div class="allmenu">
  <div class="container">
       <?php include("other_header.php"); ?>

</br>
</br></br>
  <section>
  <h2>Terms & Conditions</h2>
  <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder
     as applicable and the amended provisions pertaining to electronic records in various statutes as amended 
     by the Information Technology Act, 2000. This electronic record is generated by a computer system and does
      not require any physical or digital signatures.</p>

  <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology 
    (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy 
    and Terms of Use for access or usage of domain name <a href="https://www.vskbrothers.com">www.vskbrothers.com</a> ,
       including the related mobile site and mobile application (hereinafter referred to as “Platform”).</p>

  <p>The Platform is owned by <strong>VSK Brothers</strong>.</p>

  <p>Your use of the Platform and services and tools are governed by the following terms and conditions
     ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein 
     by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to
      the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner 
      and these terms and conditions including the policies constitute Your binding obligations with Platform Owner.</p>

  <p>These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, “Services”). 
    Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by
     the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason.
      It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>

  <p>For the purpose of these Terms of Use, wherever the context so requires "you", “your” or "user" shall mean any natural 
    or legal person who has agreed to become a user/buyer on the Platform.</p>

  <p><strong>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS 
    UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</strong></p>

  <h3>Use of Services</h3>
  <ul>
    <li>You agree to provide true, accurate and complete information during and after registration and shall be responsible 
      for all acts done through the use of your registered account on the Platform.</li>
    <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance,
       completeness or suitability of the information and materials offered on this website or through the Services.</li>
    <li>Such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such 
      inaccuracies or errors to the fullest extent permitted by law.</li>
    <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall
       not be liable to you in any manner.</li>
    <li>You are required to independently assess and ensure that the Services meet your requirements.</li>
    <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have 
      any authority to claim any intellectual property rights, title, or interest in its contents including but not 
      limited to design, layout, look and graphics.</li>
    <li>Unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
    <li>You agree to pay us the charges associated with availing the Services.</li>
    <li>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms,
       or Indian or local laws.</li>
    <li>The Platform and the Services may contain links to third-party websites. On accessing these links, you will be governed
       by the terms of such third-party websites.</li>
    <li>You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding
       and enforceable contract with the Platform Owner for the Services.</li>
  </ul>

  <h3>Indemnification</h3>
  <p>You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies and their respective officers,
     directors, agents, and employees, from any claim, demand, or actions including reasonable attorneys’ fees, made by any 
     third party or penalty imposed due to or arising out of Your breach of these Terms of Use, Privacy Policy or other policies
     , or violation of any law or rights of a third party.</p>

  <h3>Limitation of Liability</h3>
  <p>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages,
     including without limitation damages for loss of profits, business interruption, loss of business opportunities, data, 
     or economic interests.</p>
  <p>In all events, the Platform Owner’s liability shall not exceed the amount paid by You for using the Services giving rise 
    to the cause of action or Rupees One Hundred (Rs. 100), whichever is less.</p>

  <h3>Force Majeure</h3>
  <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an 
    obligation if performance is prevented or delayed by a force majeure event.</p>

  <h3>Governing Law & Jurisdiction</h3>
  <p>These Terms and any dispute or claim relating to it shall be governed by and construed in accordance with the laws of India.
     All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <strong>
      Tamil Nadu</strong>.</p>

  <h3>Contact Information</h3>
  <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>


  </section>

	  <?php include("footer.php"); ?>


</body></html>

